config/routes.rb
Rails.application.routes.draw do
  
  resources :players
  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :users do
     member do
       get :delete
     end
   end
  
   resources :scorecards do
     member do
      get :delete
     end
   end
  
  resources :courses do
     member do
      get :delete
     end
   end
  
  resources :players do
     member do
      get :delete
     end
   end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ActiveRecord::Base
  
  has_many :scorecards
  has_many :players
end

app/models/page.rb
class Page < ApplicationRecord
  
end

app/models/pages.rb
class Page < ApplicationRecord
  
end

app/models/player.rb
class Player < ApplicationRecord
  
  has_many :courses
  has_many :scorecards
end

app/models/scorecard.rb
class Scorecard < ActiveRecord::Base
  validates :player, presence: true
  scope :sorted, lambda { order("position ASC")}
  
  has_many :courses
  has_many :players
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  
  protect_from_forgery
#  skip_before_action :verify_authenticity_token, only: [:edit, :new, :destroy]
 
    layout 'admin'
  
  def index
    @courses = Course.paginate(:page => params[:page], per_page: 4)
  end
  
  def new
  end
  
  def create
    @course = Course.new(course_params)
      respond_to do |format|
      if @course.save
        flash[:notice] = "Course created."
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update
		@course = Course.find(params[:id])
        if @course.update(course_params)
            flash[:notice] = "Course created."
            redirect_to course_path(@course)
        else
          render 'edit' 
       end
  end
  
  def destroy
    @course = Course.find(params[:id])
    @course.destroy
    flash[:notice] = "Course was successfully deleted"
    redirect_to courses_path
  end
  
  def edit
    @course = Course.find(params[:id])
    flash[:notice] = "Course was successfully Changed"
  end
  
  def show
    @course = Course.find(params[:id])
  end
  
  def card_total
    @courses = Course.all
  end
  
  private
  
    def set_course
      @course = Course.find(params[:id])
    end

    def course_params
      params.require(:course).permit(:id, :name,
    :par_1,
    :par_2,
    :par_3,
    :par_4,
    :par_5,
    :par_6,
    :par_7,
    :par_8,
    :par_9,
    :par_10,
    :par_11,
    :par_12,
    :par_13,
    :par_14,
    :par_15,
    :par_16,
    :par_17,
    :par_18, 
    :total_par,
    :yardage_1,
    :yardage_2,
    :yardage_3,
    :yardage_4,
    :yardage_5,
    :yardage_6,
    :yardage_7,
    :yardage_8,
    :yardage_9,
    :yardage_10,
    :yardage_11,
    :yardage_12,
    :yardage_13,
    :yardage_14,
    :yardage_15,
    :yardage_16,
    :yardage_17,
    :yardage_18,
    :total_yardage,
    :tees)
    end
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  layout 'admin'
  def home
  end
  
  def about
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  protect_from_forgery
#  skip_before_action :verify_authenticity_token, only: [:edit, :new, :destroy]

  layout 'admin'
  
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
     @player = Player.find(params[:id])
  end

 
  def new
  end

  def edit
    @player = Player.find(params[:id])
    flash[:notice] = "Player was successfully Changed"
  end

  def create
    @player = Player.new(player_params)
      if @player.save
        flash[:success]= 'Player was successfully created.' 
        redirect_to players_path 
      else
         render 'show' 
      end
  end

  def update
    @player = Player.find(params[:id])
    if @player.update(player_params)
        flash[:notice] = "Player name was successfully updated"
        redirect_to player_path(@player)
    else
        render 'edit'    
    end
  end

  def destroy
    @player = Player.find(params[:id])
    @player.destroy
    flash[:notice] = 'Player was successfully delete.' 
      redirect_to players_path
  end
  
  private
   
    def set_player
      @player = Player.find(params[:id])
    end

    def player_params
      params.require(:player).permit(:player_name, :status, :profile, :accomplishments)
    end
end

app/controllers/scorecards_controller.rb
class ScorecardsController < ApplicationController
 before_action :set_scorecard, only: [:show, :edit, :update, :destroy]
  protect_from_forgery
#  skip_before_action :verify_authenticity_token, only: [:edit, :new, :destroy]
  
  layout 'admin'

  
  def index 
      @scorecards = Scorecard.paginate(:page => params[:page],  per_page: 5) 
  end
  
  def show
    @scorecard = Scorecard.find(params[:id])
  end
 
  def new
    @scorecard = Scorecard.new
  end
 
  def edit
    @scorecard = Scorecard.find(params[:id])
    flash[:notice] = "Scorecard was successfully Changed"
  end

  def create
    @scorecard = Scorecard.create(scorecard_params)
      if @scorecard.save
        flash[:notice] = "Scorecard created."
        redirect_to scorecards_path(@scorecard)
      else
         render 'new' 
    end
  end
 
  def update
    if @scorecard.update(scorecard_params)
        flash[:success] = "Scorecard name was successfully updated"
        redirect_to scorecard_path(@scorecard)
    else
        render 'edit'
    end
  end
  
  def destroy
    @scorecard.destroy
    flash[:notice] = "Scorecard was successfully deleted"
    redirect_to scorecards_path
  end

   def total
     @total = Total.find(params[:id])
      @total.save
#    total = Total.sort {|b1,b2| b2<=>b1 }
  end
  
  
  private
  
    def set_scorecard
      @scorecard = Scorecard.find(params[:id])
  
    end

    def scorecard_params
      params.require(:scorecard).permit(:player, :hole_1, :hole_2, :hole_3, :hole_4, :hole_5, :hole_6, :hole_7, :hole_8, :hole_9, :hole_10, :hole_11, :hole_12, :hole_13, :hole_14, :hole_15, :hole_16, :hole_17, :hole_18, :total, :round_one, :round_two, :round_three, :round_final)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/scorecards_helper.rb
module ScorecardsHelper

  
end

app/views/courses/_list_of_courses.html.erb
<% @courses.each do |course| %>
    <tr>
      <th><%= course.name %></th>
      <td><%= course.par_1 %></td>
      <td><%= course.par_2 %></td>
      <td><%= course.par_3 %></td>
      <td><%= course.par_4 %></td>
      <td><%= course.par_5 %></td>
      <td><%= course.par_6 %></td>
      <td><%= course.par_7 %></td>
      <td><%= course.par_8 %></td>
      <td><%= course.par_9 %></td>
      <td><%= front_par = [course.par_1.to_i, course.par_2.to_i, course.par_3.to_i, course.par_4.to_i, course.par_5.to_i, course.par_6.to_i, course.par_7.to_i, course.par_8.to_i, course.par_9.to_i].inject {|memo, n| memo + n} %> </td>
      <td><%= course.par_10 %></td>
      <td><%= course.par_11 %></td>
      <td><%= course.par_12 %></td>
      <td><%= course.par_13 %></td>
      <td><%= course.par_14 %></td>
      <td><%= course.par_15 %></td>
      <td><%= course.par_16 %></td>
      <td><%= course.par_17 %></td>
      <td><%= course.par_18 %></td>
      <td><%= back_par = [course.par_10.to_i, course.par_11.to_i, course.par_12.to_i, course.par_13.to_i, course.par_14.to_i, course.par_15.to_i, course.par_16.to_i, course.par_17.to_i, course.par_18.to_i].inject(0) {|sum, x| sum + x} %>
      <td>
        <% @par_total = [course.par_1.to_i, course.par_2.to_i, course.par_3.to_i, course.par_4.to_i, course.par_5.to_i, course.par_6.to_i, course.par_7.to_i, course.par_8.to_i, course.par_9.to_i, course.par_10.to_i, course.par_11.to_i, course.par_12.to_i, course.par_13.to_i, course.par_14.to_i, course.par_15.to_i, course.par_16.to_i, course.par_17.to_i, course.par_18.to_i].inject(0) {|sum, x| sum + x} %>
        <%= @par_total %>
      </td>
      <a></a>
      <td class="actions"><%= link_to 'Edit', edit_course_path(course) %></td>
      <a></a>
      <td class="actions"><%= link_to 'Show', course_path(course) %></td>
    <tr>
      <td><i><%= course.tees %></i></td>
      <td><%= course.yardage_1 %></td>
      <td><%= course.yardage_2 %></td>
      <td><%= course.yardage_3 %></td>
      <td><%= course.yardage_4 %></td>
      <td><%= course.yardage_5 %></td>
      <td><%= course.yardage_6 %></td>
      <td><%= course.yardage_7 %></td>
      <td><%= course.yardage_8 %></td>
      <td><%= course.yardage_9 %></td>
      <td><%= front_yardage = [course.yardage_1.to_i, course.yardage_2.to_i, course.yardage_3.to_i, course.yardage_4.to_i, course.yardage_5.to_i, course.yardage_6.to_i, course.yardage_7.to_i, course.yardage_8.to_i, course.yardage_9.to_i].inject {|memo, n| memo + n} %> </td>
      <td><%= course.yardage_10 %></td>
      <td><%= course.yardage_11 %></td>
      <td><%= course.yardage_12 %></td>
      <td><%= course.yardage_13 %></td>
      <td><%= course.yardage_14 %></td>
      <td><%= course.yardage_15 %></td>
      <td><%= course.yardage_16 %></td>
      <td><%= course.yardage_17 %></td>
      <td><%= course.yardage_18 %></td>
      <td><%= back_yardage = [course.yardage_10.to_i, course.yardage_11.to_i, course.yardage_12.to_i, course.yardage_13.to_i, course.yardage_14.to_i, course.yardage_15.to_i, course.yardage_16.to_i, course.yardage_17.to_i, course.yardage_18.to_i].inject(0) {|sum, x| sum + x} %>
      <td>
        <% @yardage_total = [course.yardage_1.to_i, course.yardage_2.to_i, course.yardage_3.to_i, course.yardage_4.to_i, course.yardage_5.to_i, course.yardage_6.to_i, course.yardage_7.to_i, course.yardage_8.to_i, course.yardage_9.to_i, course.yardage_10.to_i, course.yardage_11.to_i, course.yardage_12.to_i, course.yardage_13.to_i, course.yardage_14.to_i, course.yardage_15.to_i, course.yardage_16.to_i, course.yardage_17.to_i, course.yardage_18.to_i].inject(0) {|sum, x| sum + x} %>
        <%= @yardage_total %>
      </td>

      <a></a>
      <td class="actions"><%= link_to 'Delete', course_path(course), method: :delete, data: {confirm: "Are you sure?"} %></td>
    </tr>

<% end %>

app/views/courses/_par_total.html.erb
<a><%= form_for :course, url: courses_path do |f| %>

      <%= @par_total = [@course.par_1.to_i, @course.par_2.to_i, @course.par_3.to_i, @course.par_4.to_i, @course.par_5.to_i, @course.par_6.to_i, @course.par_7.to_i, @course.par_8.to_i, @course.par_9.to_i, @course.par_10.to_i, @course.par_11.to_i, @course.par_12.to_i, @course.par_13.to_i, @course.par_14.to_i, @course.par_15.to_i, @course.par_16.to_i, @course.par_17.to_i, @course.par_18.to_i].inject(0) {|sum, x| sum + x} %>
  <% end %>

</a>

app/views/courses/_par_yard_output.html.erb
<table>
          <td>Player</td><%= render 'scorecards/hole_number_headings' %>
          <tr>
            <th><%= @course.name %></th>
            <td><%= @course.par_1 %></td>
            <td><%= @course.par_2 %></td>
            <td><%= @course.par_3 %></td>
            <td><%= @course.par_4 %></td>
            <td><%= @course.par_5 %></td>
            <td><%= @course.par_6 %></td>
            <td><%= @course.par_7 %></td>
            <td><%= @course.par_8 %></td>
            <td><%= @course.par_9 %></td>
            <td><%= @course.par_10 %></td>
            <td><%= @course.par_11 %></td>
            <td><%= @course.par_12 %></td>
            <td><%= @course.par_13 %></td>
            <td><%= @course.par_14 %></td>
            <td><%= @course.par_15 %></td>
            <td><%= @course.par_16 %></td>
            <td><%= @course.par_17 %></td>
            <td><%= @course.par_18 %></td>
            <th><%= render 'par_total' %></th>
          </tr>
          <tr>
            <td><i><%= @course.tees %></i></td>
            <td><%= @course.yardage_1 %></td>
            <td><%= @course.yardage_2 %></td>
            <td><%= @course.yardage_3 %></td>
            <td><%= @course.yardage_4 %></td>
            <td><%= @course.yardage_5 %></td>
            <td><%= @course.yardage_6 %></td>
            <td><%= @course.yardage_7 %></td>
            <td><%= @course.yardage_8 %></td>
            <td><%= @course.yardage_9 %></td>
            <td><%= @course.yardage_10 %></td>
            <td><%= @course.yardage_11 %></td>
            <td><%= @course.yardage_12 %></td>
            <td><%= @course.yardage_13 %></td>
            <td><%= @course.yardage_14 %></td>
            <td><%= @course.yardage_15 %></td>
            <td><%= @course.yardage_16 %></td>
            <td><%= @course.yardage_17 %></td>
            <td><%= @course.yardage_18 %></td>
            <th><%= render 'yardage_total' %></th>
          </tr>
        </table>

app/views/courses/_pars_input.html.erb
<tr><%= form_for :course, url: courses_path do |f| %></tr>
      <tr>
        <th><%= f.text_field :name %></th>
        <td><%= f.text_field :par_1, :style => "width: 16px;" %></td>
        <td><%= f.text_field :par_2, :style => "width: 16px;" %></td>
        <td><%= f.text_field :par_3, :style => "width: 16px;" %></td>
        <td><%= f.text_field :par_4, :style => "width: 16px;" %></td>
        <td><%= f.text_field :par_5, :style => "width: 16px;" %></td>
        <td><%= f.text_field :par_6, :style => "width: 16px;" %></td>
        <td><%= f.text_field :par_7, :style => "width: 16px;" %></td>
        <td><%= f.text_field :par_8, :style => "width: 16px;" %></td>
        <td><%= f.text_field :par_9, :style => "width: 16px;" %></td>
        <td><%= f.text_field :par_10, :style => "width: 16px;" %></td>
        <td><%= f.text_field :par_11, :style => "width: 16px;" %></td>
        <td><%= f.text_field :par_12, :style => "width: 16px;" %></td>
        <td><%= f.text_field :par_13, :style => "width: 16px;" %></td>
        <td><%= f.text_field :par_14, :style => "width: 16px;" %></td>
        <td><%= f.text_field :par_15, :style => "width: 16px;" %></td>
        <td><%= f.text_field :par_16, :style => "width: 16px;" %></td>
        <td><%= f.text_field :par_17, :style => "width: 16px;" %></td>
        <td><%= f.text_field :par_18, :style => "width: 16px;" %></td>

      </tr>
      <br/>
  <% end %>

app/views/courses/_yardage_input.html.erb
 <tr><%= form_for :course, url: courses_path do |f| %></tr>  
  <th><%= f.text_field :tees %></th>
  <td><%= f.text_field :yardage_1, :style => "width: 30px;" %></td>
  <td><%= f.text_field :yardage_2, :style => "width: 25px;"  %></td>
  <td><%= f.text_field :yardage_3, :style => "width: 25px;"  %></td>
  <td><%= f.text_field :yardage_4, :style => "width: 25px;"  %></td>
  <td><%= f.text_field :yardage_5, :style => "width: 25px;"  %></td>
  <td><%= f.text_field :yardage_6, :style => "width: 25px;"  %></td>
  <td><%= f.text_field :yardage_7, :style => "width: 25px;"  %></td>
  <td><%= f.text_field :yardage_8, :style => "width: 25px;"  %></td>
  <td><%= f.text_field :yardage_9, :style => "width: 25px;"  %></td>
  <td><%= f.text_field :yardage_10, :style => "width: 25px;"  %></td>
  <td><%= f.text_field :yardage_11, :style => "width: 25px;"  %></td>
  <td><%= f.text_field :yardage_12, :style => "width: 25px;"  %></td>
  <td><%= f.text_field :yardage_13, :style => "width: 25px;"  %></td>
  <td><%= f.text_field :yardage_14, :style => "width: 25px;"  %></td>
  <td><%= f.text_field :yardage_15, :style => "width: 25px;"  %></td>
  <td><%= f.text_field :yardage_16, :style => "width: 25px;"  %></td>
  <td><%= f.text_field :yardage_17, :style => "width: 25px;"  %></td>
  <td><%= f.text_field :yardage_18, :style => "width: 25px;"  %></td>

<% end %>    
        

app/views/courses/_yardage_total.html.erb
<a><%= form_for :course, url: courses_path  do |f| %>

<%= @yardage_total = [@course.yardage_1.to_i, @course.yardage_2.to_i, @course.yardage_3.to_i, @course.yardage_4.to_i, @course.yardage_5.to_i, @course.yardage_6.to_i, @course.yardage_7.to_i, @course.yardage_8.to_i, @course.yardage_9.to_i, @course.yardage_10.to_i, @course.yardage_11.to_i, @course.yardage_12.to_i, @course.yardage_13.to_i, @course.yardage_14.to_i, @course.yardage_15.to_i, @course.yardage_16.to_i, @course.yardage_17.to_i, @course.yardage_18.to_i].inject(0) {|sum, x| sum + x} %>
<% end %>

</a>

app/views/courses/edit.html.erb
<div class="center jumbotron">
  <h1>Edit Course</h1>

  <%= form_for @course do |f| %>
      <table>
        <tr>
          <td>Player</td><%= render 'scorecards/hole_number_headings' %></tr>
        <%= render 'pars_input' %>
        <%= render 'yardage_input' %>
      </table>
      <td class="form-buttons"><%= f.submit("Save Edit") %></td>
  <% end %>

  <%= link_to "back to courses listing", courses_path %>

</div>

app/views/courses/index.html.erb
<div class="center jumbotron">
  <h1>Courses</h1>
  <body>
  <div id="main-container" class="container-fluid">
    <div class="row">
      <div id="main-content" class="col-xs-9">
        <!--  main content -->
        <table class="table" summary="Scorecard list">
          <h2>List of Courses</h2>
          <br/>
          <%= link_to "Add New Course", new_course_path %>
          <tr class="header">
            <td></td><%= render 'shared/list_heading' %>
          </tr>
          <tr>
            <%= render 'list_of_courses' %>
          </tr>
        </table>
        
        <%= will_paginate @course %>
    
        <%= link_to "Go to Scorecard", scorecards_path %>
        <br/>
        <%= link_to "Home", root_path %>
      </div>
    </div>
    <%= yield %>
  </div>
  </body>
</div>

app/views/courses/new.html.erb
<div class="center jumbotron">
  <h1>New Course</h1>

  <%= form_for Course.new do |f| %>
      <table>
        <tr>
          <th>Name of Course</th>
          <%= render 'scorecards/hole_number_headings' %> </tr>
        <%= render 'pars_input' %>
        <%= render 'yardage_input' %>
      </table>

      <td class="form-buttons"><%= f.submit("Publish Numbers") %></td>
  <% end %>
  <br/>
  <%= link_to "back to Courses listing", courses_path %>  <br/>
  <%= link_to "back to scorecards listing", scorecards_path %>

</div>

app/views/courses/show.html.erb
<div class="center jumbotron">
  <table>
    <h2> Show Courses</h2>
    <%= form_for :course do |f| %>
        <%= render 'par_yard_output' %>
    <% end %>
    <%= link_to 'Edit this course', edit_course_path(@course) %>  |
    <%= link_to 'Back to courses listing', courses_path %>
  </table>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spirit Creek</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tags %>
  
<!--
 
  <link rel="stylesheet" type="text/css" href="assets/stylesheets/custom.css">
-->



</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">MadHatterCreek</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active">
        <%= link_to 'Home', root_path %> 
      </li>
      <li><%= link_to 'Scorecard', scorecards_path %></li>
          <li><%= link_to 'Course Layout', courses_path %></li>
      <li><%= link_to 'About Page', about_path %></li>
      <li><%= link_to 'Player Registration', players_path %></li>
    </ul>
  </div>
</nav>

  

<% if !flash[:notice].blank? %>
    <div class="notice">
      <%= flash[:notice] %>
    </div>
<% end %>
<%= yield %>


<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>


<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spirit Creek</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'shared/navigation' %>
<%= yield %>
<!--    = debug(params) if Rails.env.development? %>-->
</body>
</html>

app/views/pages/_mission_statement.html.erb
<h4>Our Mission Statement</h4>


<p> It's simple....

  Work harder.
  Give more. Ask not. - unknown women
  <br/>
  <br/>

  Do. Or do not. There is no try.
  <br/>
  Fall if you will, but rise you must.
  – Yoda
</p>

app/views/players/index.html.erb
<div class="center jumbotron">
 
  
 <h4>Players</h4>
  <body>
  <div id="main-container" class="container-fluid">
    <div class="row"> 
        <table class="table" >
          <th>Player</th>
          <th>Status</th>
          <th>Profile</th>  
             <td><%= link_to 'New Player', new_player_path %></td>
             <tr>
              <% @players.each do |player| %>
              <th><%= player.player_name %></th>
              <th><%= player.status %></th>
              <th><%= player.profile %></th>
              <td><%= link_to 'Show', player %></td>
              <td><%= link_to 'Edit', edit_player_path(player) %></td>
              <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
            <% end %>
          
          
         
        </table>
    </div>
    <%= yield %>
  
  </div>
  </body>

  
</div>

app/views/players/show.html.erb
<div class="center jumbotron">
  <body>
   <div class="container">
    <h3>Player's Profile</h3>       
    <div class="panel-group">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title">
            <a data-toggle="collapse" href="#collapse1"> 
             <%= form_for :player do |f| %>
            <th><%= @player.player_name %></th>
            </a>
          </h4>
        </div>
        <div id="collapse1" class="panel-collapse collapse">
          <ul class="list-group"> 
            <li><%= @player.profile %></li>
            <li><%= @player.accomplishments %></li>
            <li><%= @player.status %></li>
          </ul>
          <div class="panel-footer"></div>
        </div>    
      </div>
    </div>
    <%= link_to 'Edit', edit_player_path(@player) %> |
    <%= link_to 'Back', players_path %>
    <% end %> 
  </div>    
  </body>
</div>

app/views/scorecards/_list_of_scores.html.erb
<% @scorecards.order(:total).each do |scorecard|  %>

<tr>
  
    <td><%= scorecard.player %></td>
    <td><%= scorecard.hole_1 %></td>
    <td><%= scorecard.hole_2 %></td>
    <td><%= scorecard.hole_3 %></td>
    <td><%= scorecard.hole_4 %></td>
    <td><%= scorecard.hole_5 %></td>
    <td><%= scorecard.hole_6 %></td>
    <td><%= scorecard.hole_7 %></td>
    <td><%= scorecard.hole_8 %></td>
    <td><%= scorecard.hole_9 %></td>
    <td><%= front = [
      scorecard.hole_1.to_i, 
      scorecard.hole_2.to_i, 
      scorecard.hole_3.to_i, 
      scorecard.hole_4.to_i, 
      scorecard.hole_5.to_i, 
      scorecard.hole_6.to_i, 
      scorecard.hole_7.to_i, 
      scorecard.hole_8.to_i, 
      scorecard.hole_9.to_i].inject(0) {|sum, x| sum + x} %> </td>
    <td><%= scorecard.hole_10 %></td>
    <td><%= scorecard.hole_11 %></td>
    <td><%= scorecard.hole_12 %></td>
    <td><%= scorecard.hole_13 %></td>
    <td><%= scorecard.hole_14 %></td>
    <td><%= scorecard.hole_15 %></td>
    <td><%= scorecard.hole_16 %></td>
    <td><%= scorecard.hole_17 %></td>
    <td><%= scorecard.hole_18 %></td>
    <td><%= back = [
      scorecard.hole_10.to_i, 
      scorecard.hole_11.to_i, 
      scorecard.hole_12.to_i, 
      scorecard.hole_13.to_i, 
      scorecard.hole_14.to_i, 
      scorecard.hole_15.to_i, 
      scorecard.hole_16.to_i, 
      scorecard.hole_17.to_i, 
      scorecard.hole_18.to_i].inject(0) {|sum, x| sum + x} %>
    <td><%= @total = [
      scorecard.hole_1.to_i, 
      scorecard.hole_2.to_i, 
      scorecard.hole_3.to_i, 
      scorecard.hole_4.to_i, 
      scorecard.hole_5.to_i, 
      scorecard.hole_6.to_i, 
      scorecard.hole_7.to_i, 
      scorecard.hole_8.to_i, 
      scorecard.hole_9.to_i, 
      scorecard.hole_10.to_i, 
      scorecard.hole_11.to_i, 
      scorecard.hole_12.to_i, 
      scorecard.hole_13.to_i, 
      scorecard.hole_14.to_i, 
      scorecard.hole_15.to_i, 
      scorecard.hole_16.to_i, 
      scorecard.hole_17.to_i, 
      scorecard.hole_18.to_i].inject(0) {|sum, x| sum + x} %>
    </td>
    <td><%= link_to 'Edit', edit_scorecard_path(scorecard) %></td>
    <td><%= link_to 'Show', scorecard_path(scorecard) %></td>
    <td><%= link_to 'Delete', scorecard_path(scorecard), 
        method: :delete, data: {confirm: "Are you sure?"} %></td>


<% end %>

app/views/scorecards/index.html.erb
<div class="center jumbotron">
 <head>
  
 <h4>List of Scorecards</h4>
 </head>
  <body>
  <div id="main-container" class="container-fluid">
    <div class="row"> 
        <table class="table" summary="Scorecard list">
          <tr class="header">
            <th>Player</th>
            <%= render 'shared/list_heading' %>
          </tr>
          <tr> <%= render 'par_heading' %></tr>
          <tr>
            <%= render 'list_of_scores' %>
          </tr>
           <%= link_to "Add New Scorecard", new_scorecard_path %><br/>
          <%= will_paginate %>
        </table>
    </div>
    <%= yield %>
  
  </div>
  </body>
</div>

app/views/scorecards/show.html.erb
<div class="center jumbotron">
  <table>
    <h2> Show Scorecards</h2>
    <%= form_for :scorecard do |f| %>
        <%= render 'scores_output' %>
    <% end %>
    <%= link_to 'Edit this scorecard', edit_scorecard_path(@scorecard) %>  |
    <%= link_to 'Back to scorecards listing', scorecards_path %>
  </table>
</div>